@echo off
title Flutter Clean Dev Server
echo Starting Device Mirror...
start cmd /k "C:\Users\Lenovo\Desktop\device-mirror\run-mirror.bat"
echo ====================================================
echo Clean cache (flutter clean)...
echo ====================================================
call flutter clean
echo.
echo flutter pub get...
call flutter pub get
echo.
echo Starting the App...
start cmd /k "title AI Patcher && dart run tool\ai_patcher.dart"
echo Starting the App...
cmd /k "dart run tool\dev_server.dart"